//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextNarrator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ACResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ACResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextNarrator.ACResources", typeof(ACResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        internal static string Age_Label_TXT {
            get {
                return ResourceManager.GetString("Age_Label_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear_Button_TXT {
            get {
                return ResourceManager.GetString("Clear_Button_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap contextmenu_Copy_Icon {
            get {
                object obj = ResourceManager.GetObject("contextmenu_Copy_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap contextmenu_Cut_Icon {
            get {
                object obj = ResourceManager.GetObject("contextmenu_Cut_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap contextmenu_Paste_Icon {
            get {
                object obj = ResourceManager.GetObject("contextmenu_Paste_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap contextmenu_SelectAll_Icon {
            get {
                object obj = ResourceManager.GetObject("contextmenu_SelectAll_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture:.
        /// </summary>
        internal static string Culture_Label_TXT {
            get {
                return ResourceManager.GetString("Culture_Label_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description_Label_TXT {
            get {
                return ResourceManager.GetString("Description_Label_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name_Label_TXT {
            get {
                return ResourceManager.GetString("Name_Label_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause_Button_TXT {
            get {
                return ResourceManager.GetString("Pause_Button_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume_Button_TXT {
            get {
                return ResourceManager.GetString("Resume_Button_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a voice ....
        /// </summary>
        internal static string SelectVoice_ComboBox_TXT {
            get {
                return ResourceManager.GetString("SelectVoice_ComboBox_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Voice ....
        /// </summary>
        internal static string SelectVoice_Label_TXT {
            get {
                return ResourceManager.GetString("SelectVoice_Label_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak.
        /// </summary>
        internal static string Speak_Button_TXT {
            get {
                return ResourceManager.GetString("Speak_Button_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Options:.
        /// </summary>
        internal static string SpeechOptions_Label_TXT {
            get {
                return ResourceManager.GetString("SpeechOptions_Label_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        internal static string Speed_Label_TXT {
            get {
                return ResourceManager.GetString("Speed_Label_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop / Cancel.
        /// </summary>
        internal static string StopCancel_Button_TXT {
            get {
                return ResourceManager.GetString("StopCancel_Button_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to read ....
        /// </summary>
        internal static string TextToRead_Label_TXT {
            get {
                return ResourceManager.GetString("TextToRead_Label_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input text for narrator to read ....
        /// </summary>
        internal static string TextToRead_Textbox_TXT {
            get {
                return ResourceManager.GetString("TextToRead_Textbox_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume:.
        /// </summary>
        internal static string Volume_Label_TXT {
            get {
                return ResourceManager.GetString("Volume_Label_TXT", resourceCulture);
            }
        }
    }
}
